export const Colors = {
    primary: "#1E3E62",
    warning: "#FF6500",

    dark: {
        text: "#EEEEEE",
        title: "#e2f2ff",
        background: "#222222",
        navBackground: "#121214",
        controlsBackground: "#362F4F",
        button: "#d7edff",
        actionButton: "#E4FF30",
        stopButton: "#FF4500",
        homeButton: "#008BFF",
        buttonHover: "#96a5b0",
        actionButtonHover: "#89991d",
        buttonText: "#071C21", 
        svgStrokeColor: "#ffffffff",
        canvasBackground: "#111111",
        colorPickerDefault: "white",
        mutedText: "#d8d7d7ff",
        boxShadowColor: "white",
    },

    light: {
        text: "#242424ff",
        title: "#362F4F",
        background: "#FFFFFF",
        navBackground: "#FFFFFF",
        controlsBackground: "#362F4F",
        button: "#008BFF",
        actionButton: "#008BFF",
        stopButton: "#FF4500",
        homeButton: "#1E3E62",
        buttonHover: "#005f9e",
        actionButtonHover: "#005f9e",
        buttonText: "black", 
        svgStrokeColor: "black",
        canvasBackground: "#EEEEEE",
        colorPickerDefault: "black",
        mutedText: "#202020ff",
        boxShadowColor: "black",
    },

}