export const Colors = {
    primary: "#1E3E62",
    warning: "#FF6500",

    dark: {
        text: "#FEFBE2",
        title: "#A4D100",
        background: "#222222",
        navBackground: "#121214",
        controlsBackground: "#362F4F",
        button: "#FEFBE2",
        buttonHover: "#c0bdaa",
        buttonPressed: "#9d9b8c",
        actionButton: "#A4D100",
        actionButtonHover: "#5EA500",
        actionButtonPressed: "#457a00",
        stopButton: "#FF4500",
        homeButton: "#0A0A0A",
        buttonText: "#0A0A0A", 
        svgStrokeColor: "#ffffffff",
        canvasBackground: "rgba(0,0,0,0.5)",
        colorPickerDefault: "white",
        mutedText: "#d8d7d7ff",
        boxShadowColor: "white",
        border: "#212025",
        landmarkPoints: "#FF4500",
        landmarkConnectors: "#CBE64E",
    },

    light: {
        text: "#EEEEEE",
        title: "#E9F881",
        background: "#222222",
        navBackground: "#121214",
        controlsBackground: "#362F4F",
        button: "#FEFBE2",
        buttonHover: "#c0bdaa",
        buttonPressed: "#9d9b8c",
        actionButton: "#A4D100",
        actionButtonHover: "#5EA500",
        actionButtonPressed: "#457a00",
        stopButton: "#FF4500",
        homeButton: "#0A0A0A",
        buttonText: "#0A0A0A", 
        svgStrokeColor: "#ffffffff",
        canvasBackground: "#111111",
        colorPickerDefault: "white",
        mutedText: "#d8d7d7ff",
        boxShadowColor: "white",
        border: "#212025",
        landmarkPoints: "#FF4500",
        landmarkConnectors: "#CBE64E",
    },

}